export const SHOW_ALERT = 'SHOW_ALERT'
export const HIDE_ALERT = 'HIDE_ALERT'

export const FETCH_SIGN_UP = 'FETCH_AUTH_CREATE'
export const FETCH_SIGN_IN = 'FETCH_AUTH_IN'
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS'
export const FETCH_AUTH = 'FETCH_AUTH'
export const SIGN_OUT = 'SIGN_OUT'
export const CHECK_AUTH = 'CHECK_AUTH'
export const AUTH_CHECKED = 'AUTH_CHECKED'

export const OPEN_WARNING_WIN = 'OPEN_WARNING_WIN'
export const CLOSE_WARNING_WIN = 'CLOSE_WARNING_WIN'

export const FETCH_USER_DATA = 'FETCH_USER_DATA'
export const FETCH_USER_FOLLOWERS = 'FETCH_USER_FOLLOWERS'
export const FETCH_USER_FOLLOWING = 'FETCH_USER_FOLLOWING'
export const SUCCESS_USER_DATA = 'SUCCESS_USER_DATA'
export const FOLLOWERS_SUCCESS = 'FOLLOWERS_SUCCESS'
export const FOLLOWING_SUCCESS = 'FOLLOWING_SUCCESS'
export const CLEAR_USER_DATA = 'CLEAR_USER_DATA'
export const FOLLOW_USER = 'FOLLOW_USER'
export const UNFOLLOW_USER = 'UNFOLLOW_USER'

export const OPEN_ALL = 'OPEN_ALL'
export const CLOSE_ALL = 'CLOSE_ALL'

export const SEARCH_USER = 'SEARCH_USER'
export const SUCCESS_SEARCH_USER = 'SUCCESS_SEARCH_USER'